import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const bodyFont = localFont({
  src: "./fonts/TT-firs-Text-Trial-Bold.ttf",
  variable: "--body-font",
  weight: "100 500"
});
const headerFont = localFont({
  src: "./fonts/LTSuperior-Bold.otf",
  weight: "900"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bodyFont.className}`} >
        {children}
      </body>
    </html>
  );
}
