import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const bodyFont = localFont({
  src: [
    { 
      path: "./fonts/TT-firs-Text-Trial-Bold.ttf",
      weight: "500",
      
    }
    
  ],
  variable: '--font-bodyFont-'
});
const headerFont = localFont({
  src: [
    { 
      path: "./fonts/LTSuperior-Medium.otf",
      weight: "900"
    }
  ]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${headerFont.className} ${bodyFont.className}` } >
        {children}
      </body>
    </html>
  );
}
